# Generated by Django 5.2.7 on 2026-04-02 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'directive_level',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cumulative', 'Số liệu tại thời điểm báo cáo'), ('discrete', 'Số liệu trong kỳ báo cáo')], max_length=20)),
                ('register_guide', models.TextField()),
                ('submit_guide', models.TextField()),
                ('target_percent', models.FloatField()),
                ('issued_at', models.DateField()),
                ('expired_at', models.DateField()),
            ],
            options={
                'db_table': 'quota',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('object_uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
            ],
            options={
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CAP', 'Cap'), ('CAX', 'Cax')], default='CAX', max_length=255)),
                ('parent', models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='app.department')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DirectiveDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issued_at', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(null=True)),
                ('directive_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directive_documents', to='app.directivelevel')),
                ('type', models.ForeignKey(db_column='type_code', on_delete=django.db.models.deletion.PROTECT, related_name='directive_documents', to='app.documenttype')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directive_documents', to='app.storage')),
            ],
            options={
                'db_table': 'directive_document',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_departments', models.ManyToManyField(blank=True, related_name='assigned_missions', to='app.department')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='app.department')),
                ('directive_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='app.directivedocument')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_missions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'period',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uq_year_month')],
            },
        ),
        migrations.CreateModel(
            name='QuotaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('is_leader', models.BooleanField(db_index=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_assignments', to='app.department')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_assignments', to='app.quota')),
            ],
            options={
                'db_table': 'quota_assignment',
            },
        ),
        migrations.CreateModel(
            name='ReportPeriodMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('report_type', models.CharField(choices=[('MONTH', 'Báo cáo tháng'), ('QUARTER', 'Báo cáo quý'), ('HALF_YEAR', 'Báo cáo 6 tháng'), ('NINE_MONTH', 'Báo cáo 9 tháng'), ('YEAR', 'Báo cáo năm')], max_length=20)),
            ],
            options={
                'db_table': 'report_period_month',
                'ordering': ['month'],
                'constraints': [models.UniqueConstraint(fields=('month', 'report_type'), name='uq_month_type')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issued_at', models.DateField()),
                ('issued_by', models.TextField()),
                ('expired_at', models.DateField(null=True)),
                ('type', models.ForeignKey(db_column='type_code', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='app.documenttype')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='app.storage')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='MissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.PositiveSmallIntegerField()),
                ('report_year', models.PositiveSmallIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('no_work_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NOT_SENT', 'Chưa gửi'), ('APPROVED', 'Đã gửi'), ('NO_REPORT', 'Không gửi')], default='NOT_SENT', max_length=20)),
                ('mission_status', models.CharField(choices=[('IN_PROGRESS_ON_TIME', 'Đang thực hiện đúng hạn'), ('IN_PROGRESS_LATE', 'Đang thực hiện trễ hạn'), ('COMPLETED_ON_TIME', 'Hoàn thành đúng hạn'), ('COMPLETED_LATE', 'Hoàn thành trễ hạn'), ('NOT_COMPLETED_LATE', 'Chưa thực hiện trễ hạn'), ('NOT_COMPLETED_ON_TIME', 'Chưa thực hiện đúng hạn')], default='NOT_COMPLETED_ON_TIME', max_length=30)),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.mission')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mission_reports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_reports', to='app.period')),
            ],
            options={
                'db_table': 'mission_report',
                'ordering': ['-report_year', '-report_month', '-created_at'],
                'unique_together': {('mission', 'report_month', 'report_year')},
            },
        ),
        migrations.CreateModel(
            name='QuotaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('expected_value', models.BigIntegerField(null=True)),
                ('actual_value', models.BigIntegerField(null=True)),
                ('note', models.TextField(null=True)),
                ('status', models.CharField(choices=[('not_sent', 'Chưa gửi'), ('pending', 'Chờ duyệt'), ('rejected', 'Từ chối'), ('failed', 'Không đạt'), ('passed', 'Đạt')], db_index=True, max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('submit_at', models.DateTimeField(null=True)),
                ('submit_by', models.CharField(max_length=512, null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reviewed_by', models.CharField(max_length=512, null=True)),
                ('reason', models.TextField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_reports', to='app.department')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_reports', to='app.period')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_reports', to='app.quota')),
            ],
            options={
                'db_table': 'quota_report',
                'constraints': [models.UniqueConstraint(fields=('quota', 'department', 'period'), name='uq_quota_report')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=512)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('report_type', models.CharField(blank=True, choices=[('MONTH', 'Báo cáo tháng'), ('QUARTER', 'Báo cáo quý'), ('HALF_YEAR', 'Báo cáo 6 tháng'), ('NINE_MONTH', 'Báo cáo 9 tháng'), ('YEAR', 'Báo cáo năm')], max_length=20, null=True)),
                ('report_year', models.PositiveSmallIntegerField()),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='NOT_SENT', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, related_name='department_reports', to='app.department')),
                ('file', models.ForeignKey(blank=True, db_column='file_object_uid', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_reports', to='app.storage')),
            ],
            options={
                'db_table': 'department_report',
                'ordering': ['-report_year', 'month', 'department_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ck_department_report_month_range'), models.UniqueConstraint(fields=('department', 'month', 'report_type', 'report_year'), name='uq_department_report')],
            },
        ),
    ]
