# Generated by Django 5.2.7 on 2026-04-02 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentreport',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_department_report', to='app.period'),
        ),
        migrations.AddField(
            model_name='document',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_document', to='app.period'),
        ),
        migrations.AlterField(
            model_name='missionreport',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_mission', to='app.period'),
        ),
    ]
