# Generated by Django 5.2.7 on 2026-04-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_system_config_key_pk_and_history_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={
                'db_table': 'document',
                'ordering': ['-issued_at'],
                'permissions': [
                    ('read_document', 'Can read document'),
                ],
            },
        ),
    ]
