# Generated by Django 5.2.7 on 2026-04-06 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_document_read_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotaassignment',
            name='is_leader',
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quota',
            name='department',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='app.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('CAP', 'CAP'), ('CAX', 'CAX')], default='CAX', max_length=255),
        ),
        migrations.AlterField(
            model_name='missionreport',
            name='status',
            field=models.CharField(choices=[('NOT_SENT', 'Chưa gửi'), ('APPROVED', 'Đã gửi')], default='NOT_SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
