# Generated by Django 5.2.7 on 2026-04-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_quotaassignment_is_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotareport',
            name='previous_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.quotareport'),
        ),
    ]
