# Generated by Django 5.2.7 on 2026-04-13 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_quotareport_previous_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Xếp loại')),
                ('name', models.CharField(max_length=100, verbose_name='Tên xếp loại')),
                ('score_from', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm từ')),
                ('score_to', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm đến')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'db_table': 'rank',
            },
        ),
        migrations.AlterModelOptions(
            name='quotareport',
            options={'ordering': ['-period_id']},
        ),
    ]
