# Generated by Django 5.2.7 on 2026-04-14 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ranking_alter_quotareport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='score_from',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm từ'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='score_to',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm đến'),
        ),
    ]
